name: default

on:
  - push

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          ignore: DL3006

  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: clippy
        run: cargo clippy
      - name: test
        run: cargo test

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Kaniko build
        uses: aevea/action-kaniko@v0.6.0
        with:
          image: hsmtkk/improved-dollop
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          cache: true
          cache_registry: hsmtkk/improved-dollop
